# Generated by Django 3.0.8 on 2021-01-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_auto_20200712_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='language',
        ),
    ]
