# Generated by Django 3.0.8 on 2021-01-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_remove_song_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
